### ISSUE TITLE
github に push したら、ウェブページも更新されるようにしたい

### ISSUE THREAD

**Issue by mayok** [kyutech-club/web#1]

**Comment by owatan** [comment]
むしろ、Github Pages にするのが良いかもしれんね

**Comment by mayok** [comment]
Github Pages にすると，すべて Github で完結するからとても嬉しい

**Comment by owatan** [comment]
`gh-pages.club.kyutech.ac.jp` みたいなのを `kyutech-club.github.io` に向けて様子見てこ

**Comment by mayok** [comment]
Github Pages 作った http://kyutech-club.github.io/web/

すごく簡単だった

**Comment by owatan** [comment]
:+1:

**Comment by owatan** [comment]
もしブログみたいなのを作ろうとしてるのであれば、`kyutech-club/blog` みたいな (非公開) レポジトリを作って、そのレポジトリの `gh-pages` ブランチに記事を書いて、pull-req とかで内容を精査 (レビュー) しあうのが良いかもしれんね
(ブログを生成するのは、[octopress](http://octopress.org/) みたいなツールが良さそう)

**Comment by mayok** [comment]
とりあえず，Github に push したらウェブページが更新されるようになったので閉じるね
