### ISSUE TITLE
css の冗長な書き方をやめる

### ISSUE THREAD

**Issue by mayok** [kyutech-club/web#3]
```
.main .container,
.footer .container {
}
```
のような書き方を
```
.container {
}
```
に変更する

**Comment by mayok** [comment]
commit と issue を連携させると汚くなるので，やめよう

**Comment by owatan** [comment]
こういうのは、別途コーディング規約みたいなのを作ると良いかもしれんね

- [Google HTML/CSS Style Guide](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#CSS_Style_Rules)
- [「Google HTML/CSS Style Guide」を適当に和訳してみた | REFLECTDESIGN](http://re-dzine.net/2012/05/google-htmlcss-style-guide/)

**Comment by mayok** [comment]
:+1:
